/**
 * Static HTML leaderboard generator.
 *
 * Generates a self-contained HTML page with inline CSS/JS for the leaderboard.
 * Zero external dependencies at runtime — the output is a standalone file.
 *
 * @module adapters/site/html-generator
 */

import type { LeaderboardData, LeaderboardEntry } from '#core/entities/leaderboard.js';

/**
 * Generate a complete, self-contained leaderboard HTML page.
 */
export function generateLeaderboardHTML(data: LeaderboardData): string {
    const rows = data.entries.map((e, i) => generateRow(e, i + 1)).join('\n');
    const domainHeaders = data.meta.domains.map((d) => `<th>${d}</th>`).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>chainskills Agent Arena — Leaderboard</title>
<style>
:root {
  --bg: #0d1117; --surface: #161b22; --border: #30363d;
  --text: #e6edf3; --text-dim: #8b949e; --accent: #58a6ff;
  --green: #3fb950; --yellow: #d29922; --red: #f85149;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); }
.container { max-width: 1200px; margin: 0 auto; padding: 2rem 1rem; }
header { text-align: center; margin-bottom: 2rem; }
header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
header h1 span { color: var(--accent); }
header p { color: var(--text-dim); font-size: 0.95rem; }
.meta { display: flex; gap: 1.5rem; justify-content: center; margin: 1rem 0; flex-wrap: wrap; }
.meta-item { background: var(--surface); border: 1px solid var(--border); border-radius: 6px; padding: 0.4rem 0.8rem; font-size: 0.85rem; }
.meta-item strong { color: var(--accent); }
table { width: 100%; border-collapse: collapse; background: var(--surface); border-radius: 8px; overflow: hidden; }
thead th { background: var(--border); padding: 0.75rem 0.5rem; text-align: left; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px; color: var(--text-dim); cursor: pointer; user-select: none; white-space: nowrap; }
thead th:hover { color: var(--accent); }
tbody td { padding: 0.6rem 0.5rem; border-top: 1px solid var(--border); font-size: 0.9rem; white-space: nowrap; }
tbody tr:hover { background: rgba(88, 166, 255, 0.05); }
.rank { font-weight: 700; color: var(--accent); width: 3rem; text-align: center; }
.model { font-weight: 600; }
.provider { font-size: 0.75rem; color: var(--text-dim); background: var(--bg); padding: 2px 6px; border-radius: 4px; margin-left: 0.3rem; }
.elo { font-weight: 700; font-variant-numeric: tabular-nums; }
.pass { font-variant-numeric: tabular-nums; }
.cost { font-variant-numeric: tabular-nums; color: var(--text-dim); }
.pareto-1 { color: var(--green); font-weight: 700; }
.pareto-2 { color: var(--yellow); }
.bar { display: inline-block; height: 8px; border-radius: 4px; background: var(--accent); min-width: 2px; }
footer { text-align: center; margin-top: 2rem; color: var(--text-dim); font-size: 0.8rem; }
footer a { color: var(--accent); text-decoration: none; }
@media (max-width: 768px) { .container { padding: 1rem 0.5rem; } table { font-size: 0.8rem; } }
</style>
</head>
<body>
<div class="container">
<header>
  <h1><span>chainskills</span> Agent Arena</h1>
  <p>Cross-domain AI agent evaluation leaderboard — ${data.totalWorkflows} workflows, ${data.meta.domains.length} domains</p>
  <div class="meta">
    <span class="meta-item">Suite <strong>v${data.suiteVersion}</strong></span>
    <span class="meta-item">Models <strong>${data.entries.length}</strong></span>
    <span class="meta-item">Runs/model <strong>${data.meta.runsPerModel}</strong></span>
    <span class="meta-item">Updated <strong>${new Date(data.updatedAt).toLocaleDateString()}</strong></span>
  </div>
</header>

<table id="leaderboard">
<thead>
  <tr>
    <th onclick="sortTable(0)">#</th>
    <th onclick="sortTable(1)">Model</th>
    <th onclick="sortTable(2)">Elo</th>
    <th onclick="sortTable(3)">Pass%</th>
    ${domainHeaders}
    <th onclick="sortTable(${4 + data.meta.domains.length})">Cost/task</th>
    <th onclick="sortTable(${5 + data.meta.domains.length})">Latency</th>
    <th onclick="sortTable(${6 + data.meta.domains.length})">Reliability</th>
    <th onclick="sortTable(${7 + data.meta.domains.length})">Pareto</th>
  </tr>
</thead>
<tbody>
${rows}
</tbody>
</table>

<footer>
  <p>Generated by <a href="https://github.com/TheWatcher01/chainskills">chainskills</a> — the Chatbot Arena for AI agents</p>
</footer>
</div>
<script>
function sortTable(col) {
  const table = document.getElementById('leaderboard');
  const tbody = table.querySelector('tbody');
  const rows = Array.from(tbody.querySelectorAll('tr'));
  const isNum = col !== 1;
  rows.sort((a, b) => {
    const aVal = a.cells[col]?.textContent?.trim() ?? '';
    const bVal = b.cells[col]?.textContent?.trim() ?? '';
    if (isNum) {
      const aNum = parseFloat(aVal.replace(/[^0-9.\\-]/g, '')) || 0;
      const bNum = parseFloat(bVal.replace(/[^0-9.\\-]/g, '')) || 0;
      return bNum - aNum;
    }
    return aVal.localeCompare(bVal);
  });
  rows.forEach(r => tbody.appendChild(r));
}
</script>
</body>
</html>`;
}

function generateRow(entry: LeaderboardEntry, rank: number): string {
    const domainCells = Object.entries(entry.domains)
        .map(([_, score]) => {
            if (!score) return '<td>-</td>';
            const pct = Math.round(score.passRate * 100);
            const barWidth = Math.max(2, Math.round(pct * 0.8));
            return `<td>${pct}% <span class="bar" style="width:${barWidth}px"></span></td>`;
        })
        .join('');

    const paretoClass = entry.paretoRank === 1 ? 'pareto-1' : entry.paretoRank <= 3 ? 'pareto-2' : '';
    const costStr = entry.costPerTask_usd > 0 ? `$${entry.costPerTask_usd.toFixed(4)}` : 'free';

    return `  <tr>
    <td class="rank">${rank}</td>
    <td class="model">${entry.model}<span class="provider">${entry.provider}</span></td>
    <td class="elo">${entry.elo}</td>
    <td class="pass">${Math.round(entry.passRate * 100)}%</td>
    ${domainCells}
    <td class="cost">${costStr}</td>
    <td>${entry.avgLatency_ms}ms</td>
    <td>${Math.round(entry.reliability * 100)}%</td>
    <td class="${paretoClass}">${entry.paretoRank === 1 ? 'Frontier' : `#${entry.paretoRank}`}</td>
  </tr>`;
}
